### ISSUE TITLE
Open file dialog looks bad

### ISSUE THREAD

**Issue by molaeiali** [snapcrafters/vscode#1]
This is how my open file dialog looks like
![screenshot-2018-05-21-19-58-45](https://user-images.githubusercontent.com/12999682/40315782-91527948-5d31-11e8-90ce-7e5cd064208c.png)
My System Info:
Arch Linux 4.16.9-1-ARCH
Cinnamon 3.8.2
GTK Theme Matcha-sea
Icon Theme Matcha

I don't think it is because of my theme and icons because this dialog is ok in other native applications

**Comment by wsalmeida** [comment]
I would like to reinforce that I am with this the icons do not appear when opening the file manager of vscode problems in my case it occurs with xubuntu

![vscode](https://user-images.githubusercontent.com/38542279/41066902-0143ccfe-69ba-11e8-9ec9-5243006e024c.png)

**Comment by seandjones92** [comment]
This is also occurring in Ubuntu 18.04 with default (Adwaita) Gnome theme
![image](https://user-images.githubusercontent.com/17571045/41257234-5477236c-6d89-11e8-9902-79510e6a0a83.png)

**Comment by thanhduong9613** [comment]
i cant type vietnamese

**Comment by diddledan** [comment]
For reference, this is due to classic confinement. The program is incorrectly loading libgdk-pixbuf-loader from the system. It should be loading all libraries from within it's own filesystem.

**Comment by Timmmm** [comment]
Mine is even worse...

![screenshot from 2018-10-28 18-44-42](https://user-images.githubusercontent.com/376842/47620399-98272880-dae1-11e8-8987-d35d6bad68a8.png)

This sort of nonsense wouldn't happen on Windows...

**Comment by skewty** [comment]
@Timmmm Apples to oranges.  SNAP packages are sandboxed.  

I don't believe VScode is available from MS in fully sandboxed form yet.

That said, the VScode SNAP still has a lot of opportunity for improvement.

[This link](https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235) contains what is likely required to "fix" the theming in the SNAP.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/vscode/pull/40

**Comment by YamiYukiSenpai** [comment]
I don't think this issue should be closed because it still looks ugly.  At least this time, I can tell which one's selected.
![screenshot_20190307_004542](https://user-images.githubusercontent.com/13153124/53934881-59e2dc80-4072-11e9-9a0d-89ba39b7721b.png)
