### ISSUE TITLE
VSCode crashing wayland

### ISSUE THREAD

**Issue by SwitchedToGitlab** [snapcrafters/vscode#10]
# Summary
Snap version of VSCode 1.26.1-1534444688 is crashing Wayland on Ubuntu 18.04.1. Reverting to 1.25.1-1531323788 resolves the issue. No issues when running Xorg. I need help troubleshooting this and opening a ticket with the right GNOME/Wayland team.

## SYMPTOM:
Opening vscode, either from the shell DESKTOP file or the command line using ```code foo```, GNOME shell crashes and the user is taken back to a login prompt.

## ENV:
Ubuntu 18.04.1 LTS x86_64 
GNOME Shell 3.28.3. 
```➔ snap --version
snap    2.35
snapd   2.35
series  16
ubuntu  18.04
kernel  4.15.0-33-generic
➔ snap list --all vscode
Name    Version            Rev  Tracking  Publisher     Notes
vscode  1.25.1-1531323788  46   stable    snapcrafters  classic
vscode  1.26.1-1534444688  52   stable    snapcrafters  disabled,classic
```

Let me know what else you may need. Thanks in advance for the help.

**Comment by SBI-** [comment]
I can confirm this behaviour. Other electron apps such as Circuit don't crash wayland. I have heard from people using [slack experiencing similar problems though](https://forum.snapcraft.io/t/wayland-crash-with-electron-2/5752/7).

**Comment by HankB** [comment]
I can confirm the same behavior on Debian Testing. Xwayland leaves a core in my home directory. I am not running vs code as a snap on Debian.
