### ISSUE TITLE
Unable to load video drivers Ubuntu 18.04.1

### ISSUE THREAD

**Issue by bendleah** [snapcrafters/vscode#15]
Hi,

When launching VSCode v1.27.2 using the snap, it fails to load the referenced video drivers with the following errors;

`
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
`

I'm using Ubuntu 18.04.1. 

Any further information required , please let me know.

**Comment by flexiondotorg** [comment]
I can't reproduce this. How are you launching vscode?

**Comment by rubberneck** [comment]
I don't get this when launching. This does show up in the `Debug Console` when i start a debugging session. It shows the same error doing `Start Debugging F5` or `Start Without Debugging Ctrl+F5`. This is on the example project created from https://code.visualstudio.com/docs/extensions/example-hello-world 

I am starting vscode from the terminal by running `vscode .` in the project directory.

This doesn't seem to keep anything from working that I can tell. 

If I can provide anymore information please let me know.

Below is the error
```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by Lednerb** [comment]
I've had the same error and found this issue.
It was displayed when running in verbose mode.

I've had the vscode installed via `snap`.

After removing the `snap` package and installing the editor natively via https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions the error does no longer occur.

You can test it by running `code --verbose .`

**Comment by schoepke** [comment]
I'm having this issue as well, albeit Ubuntu now is at 18.04.03 and VSCode at v1.39.2.
Error messages show up when runing `code --status` while an instance is running.
VSCode itself works fine. CPU usage is a bit high but that could be attributed to other troublemakers like e.g. the file watcher service :-)
