### ISSUE TITLE
Make it clear in the Ubuntu Software Center that this version has serious issues.

### ISSUE THREAD

**Issue by Timmmm** [snapcrafters/vscode#25]
As a recently returned Ubuntu user I decided to install VSCode. "I'll try the Ubuntu Software Center they're always flogging!" I thought. Sure enough it has VSCode and it looks pretty official (except the authors are "snapcrafters" rather than Microsoft. Ok I guess.

Anyway I installed it and found it has various serious bugs (broken theming, terrible default font, very slow startup). The version from Microsoft has none of these issues (well maybe the font - I'm not sure).

The listing in the store should come with a big warning to tell people that they probably want the official version for now.

**Comment by popey** [comment]
All software has bugs. If we marked every package that had bugs, they'd all be marked. You've separately filed issues for the font and startup time, for which we're appreciative. We're looking at both. I'd rather we fixed the bugs we have than steer people away from the package.
