### ISSUE TITLE
Snap is outdated

### ISSUE THREAD

**Issue by Kedstar99** [snapcrafters/vscode#29]
It's been a while since vscode 1.29.1 has been launched. The snap is still stuck with 1.29.

Is there currently a CI pipeline that triggers when vscode is updated?

**Comment by popey** [comment]
Unfortunately a technical issue in launchpad meant I had to build multiple times to get it uploaded. This is now done. Apologies for the delay.

**Comment by meddario** [comment]
@popey i was checking if there is a way to disable the notification, i noticed this: https://github.com/Microsoft/vscode/blob/8f688a4ccf7bb996475b71e13693bd5c7b1af0ee/src/vs/platform/update/electron-main/updateService.linux.ts#L81, apparently there's already a snap update check, maybe it's not working correctly. 
Tomorrow i'll clone the source code to do a better check, if there is a vscode bug i'll open an issue.

**Comment by Kedstar99** [comment]
Looking at the code and the resource, it appears to be looking for 
/snap/code/current
rather than 
/snap/vscode/current

As such I would be curious to see if this is being logged.
'update#checkForSnapUpdate(): Could not get realpath of application.'

To fix this, a sensible suggestion would be to stage the snap as /snap/code rahter than /snap/vscode at least to keep consistency maybe with the deb product.

Running this:

cat ./usr/share/code/resources/app/product.json | grep 'applicationName'
        "applicationName": "code",

It may be easier to fix with the snapcraft config here versus changing their code.

**Comment by meddario** [comment]
@Kedstar99 sorry for the delay! Yes, it's ok, glad i could help!
