### ISSUE TITLE
ENOENT: no such file or directory, lstat '/snap/code'

### ISSUE THREAD

**Issue by thiras** [snapcrafters/vscode#32]
It's Ubuntu 18.04. Fresh install. Vscode throw out `ENOENT: no such file or directory, lstat '/snap/code'` at the start. No effect noticed on usage.

**Comment by rakshans1** [comment]
Same here but my `/snap`  folder contains `/snap/vscode` folder

**Comment by Kedstar99** [comment]
Hello, I think I fixed this issue before the November release  in this PR.

https://github.com/Microsoft/vscode/pull/64392

It seems Microsoft is planning to release it's own snap version soon but the paths appear to be hardcoded.

When it gets merged hopefully things will get fixed.

**Comment by flexiondotorg** [comment]
@Kedstar99 Thank you for assisting upstream! You're PR has been merged upstream and will be reflected in this snap in due course :smiley:

**Comment by adriaanbd** [comment]
I'm experiencing this issue every time I open VS Code. What should I do to avoid this annoying pop up message? Does it have a fix? Thanks for any help.

**Comment by adriaanbd** [comment]
> I'm experiencing this issue every time I open VS Code. What should I do to avoid this annoying pop up message? Does it have a fix? Thanks for any help.

Nevermind, I fixed it with: `sudo ln -s /snap/vscode /snap/code`
