### ISSUE TITLE
Microsoft is looking to produce their own snap for VSCode

### ISSUE THREAD

**Issue by Kedstar99** [snapcrafters/vscode#34]
Hello,

I have been looking and fixing some of the issues presented with VSCode upstream. It appears that Microsoft has plans to release a snap version themselves. The current mechanism used to build the snap may not work in the future. Mainly because Microsoft is using a build mechanism such that some resources are  bundled specifically for the snap. As such, the current method of building against the deb provided may have more issues in the future. An example would be snapUpdate.sh found in vscode/resources/linux/snap which doesn't get built or provided with the deb.

To solve this problem there are a few solutions:
  
1. The current snap version can be modified to build these resources too, but I don't think this is an elegant solution as changes to the build mechanism upstream would have to be duplicated here. 
2. It is possible to try and build vscode from source, which may be missing some proprietary features that users may wish to have. Microsoft is going to release their release anyway.
3. Work with Microsoft to pass ownership and maintenance to Microsoft.

To me, option 3 makes the most sense as it doesn't really make sense to me to duplicate efforts to build the snap. I can equally understand why people may choose option 2. In any case, I was wondering if there has been any discussions over this.

Kind regards,
Krish

**Comment by Tyriar** [comment]
This can be closed, Microsoft has been talking with the Snapcraft team about this already. See issues we're tracking here https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asnap

**Comment by flexiondotorg** [comment]
Closing this issue and will assist with upstream.
