### ISSUE TITLE
vscode snap doesn't intuitively work with dotnet-sdk snap

### ISSUE THREAD

**Issue by soundconjurer** [snapcrafters/vscode#45]
This is more of a documentation issue than a technical one, I understand this isn't maintained to work by default with the snap version. However, maybe on the vscode snap page this information could be provided when working with the dotnet-sdk snap.

Also, to set the dotnet-sdk snap with an alias.

These two would seem like a match made in heaven otherwise.

**Comment by AbhishekTripathi** [comment]
I am facing same problem. First hurdle was to know that after installing the (dotnet sdk snap)[https://snapcraft.io/dotnet-sdk], the dotnet command is not available by default. One needs to invoke dotnet by using [dotnet-sdk.dotnet](https://snapcraft.io/dotnet-sdk) alias. VSCode doesn't expect dotnet invocation this way and there seems to have no way to enforce this. The only option feasible apparently is to alias dotnet or create a symlink. It should be documented well and vscode snap should work well with dotnet-sdk snap.
