### ISSUE TITLE
Can not use ibus

### ISSUE THREAD

**Issue by haunt98** [snapcrafters/vscode#47]
I install snap vscode from Ubuntu software center. I install ```ibus-unikey``` but can not use it on vscode snap. 

I think this bug is [appeared](https://github.com/snapcrafters/vscode/issues/28) before but the fix is applied only for ```fcitx``` but not ```ibus```.

**Comment by yoyoys** [comment]
After update to ubuntu 19.04, I've got same issue

**Comment by lijinglin3** [comment]
19.10 is the same, so I installed with [apt-get](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions)

Waiting for fix

**Comment by sunsetsonwheels** [comment]
I can confirm this bug still is on the latest official Snappy package (version: 5763d909, revision: 33). Using `ibus-unikey`.
