### ISSUE TITLE
Opening external links only shows a Mozilla Crash Reporter

### ISSUE THREAD

**Issue by inorick** [snapcrafters/vscode#48]
Steps to reproduce:

1. Open vscode snap
2. Click any link that is supposed to open up an external browser. For example from the release notes.

Expected result:
A new browser windows opens.

Actual result:
The Mozilla Crash Reporter opens. 

Versions:
  vscode: 1.35.1 and 1.36-insder
  vscode snap: c7d83e57 and 6520c22b
  vscode snap channel: stable and edge
  OS: Ubuntu 19.04

**Comment by arikfr** [comment]
I had the same issue both on 19.04 and 19.10 with latest vscode snap (installed via the command line with `install --classic`). 

I ended up installing Visual Studio Code with the deb package instead. Also had similar issues with Slack's snap, where it would open Firefox but without the default profile. :-(

**Comment by doc-E-brown** [comment]
It seems VSCode expects Chrome to be the default browser.  After installing Chrome and temporarily setting it to be the default browser I was able to launch links.

**Comment by ethervoid** [comment]
In my case making the Chromium default and then switching again to Firefox didn't do the trick. But I can open the links using Chromium

**Comment by jota0222** [comment]
> In my case making the Chromium default and then switching again to Firefox didn't do the trick. But I can open the links using Chromium

Thats exactly what is happening to me. It seems that vscode is expecting chrome like browser or a snap of Firefox.

I'm using Firefox Developers that has no snap.
