### ISSUE TITLE
VScode 1.26 released

### ISSUE THREAD

**Issue by hungryDev39** [snapcrafters/vscode#8]
please update the stable version to 1.26

**Comment by popey** [comment]
Thanks for letting us know @hungryDev39  - I've triggered a build. https://build.snapcraft.io/user/snapcrafters/vscode

**Comment by popey** [comment]
1.26 is now in stable for amd64 users.

**Comment by peradnya** [comment]
Version 1.26.1 already released: https://code.visualstudio.com/updates/v1_26. Thank you.

**Comment by popey** [comment]
@peradnya thanks, released.
